version: '3'
services:
  api:
    image: plant_inventory_api
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
    restart: always   
  nginx:
    image: nginx
    build:
      context: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    links:
      - api
    volumes:
      - /etc/letsencrypt/live/:/etc/letsencrypt/live
      - /etc/letsencrypt/archive/:/etc/letsencrypt/archive
    restart: always